-- Tabla estudiantes
ALTER TABLE ESTUDIANTES ADD CONSTRAINT PK_DNI_EST PRIMARY KEY (ESTUDIANTE.DNI_USU);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT NN_NOM_EST CHECK (ESTUDIANTE.NOMBRE_USU IS NOT NULL);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT NN_APE1_EST CHECK (ESTUDIANTE.APELLIDO1_USU IS NOT NULL);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT NN_TIPODOC_EST CHECK (ESTUDIANTE.TIPODOC_USU IS NOT NULL);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT NN_CORREO_EST CHECK (ESTUDIANTE.CORREO_USU IS NOT NULL);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT NN_SEXO_EST CHECK (ESTUDIANTE.SEXO_USU IS NOT NULL);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT NN_CONTRA_EST CHECK (ESTUDIANTE.CONTRASENNA_USU IS NOT NULL);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT NN_NAC_EST CHECK (ESTUDIANTE.NACIMIENTO_USU IS NOT NULL);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT NN_ESDO_EST CHECK (ESTUDIANTE.ESTADO_USU IS NOT NULL);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT UK_CORREO_EST UNIQUE (ESTUDIANTE.CORREO_USU);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT FK_TIPODOC_EST FOREIGN KEY (ESTUDIANTE.TIPODOC_USU) REFERENCES TIPODOCUMENTOS(CODIGO_TIPODOC);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT FK_SEXO_EST FOREIGN KEY (ESTUDIANTE.SEXO_USU) REFERENCES SEXOS(CODIGO_SEX);
ALTER TABLE ESTUDIANTES ADD CONSTRAINT FK_ESDO_EST FOREIGN KEY (ESTUDIANTE.ESTADO_USU) REFERENCES ESTADOS(CODIGO_ESTADO);

-- Tabla profesores
ALTER TABLE PROFESORES ADD CONSTRAINT PK_DNI_PROF PRIMARY KEY (PROFESOR.DNI_USU);
ALTER TABLE PROFESORES ADD CONSTRAINT NN_NOM_PROF CHECK (PROFESOR.NOMBRE_USU IS NOT NULL);
ALTER TABLE PROFESORES ADD CONSTRAINT NN_APE1_PROF CHECK (PROFESOR.APELLIDO1_USU IS NOT NULL);
ALTER TABLE PROFESORES ADD CONSTRAINT NN_TIPODOC_PROF CHECK (PROFESOR.TIPODOC_USU IS NOT NULL);
ALTER TABLE PROFESORES ADD CONSTRAINT NN_CORREO_PROF CHECK (PROFESOR.CORREO_USU IS NOT NULL);
ALTER TABLE PROFESORES ADD CONSTRAINT NN_SEXO_PROF CHECK (PROFESOR.SEXO_USU IS NOT NULL);
ALTER TABLE PROFESORES ADD CONSTRAINT NN_CONTRA_PROF CHECK (PROFESOR.CONTRASENNA_USU IS NOT NULL);
ALTER TABLE PROFESORES ADD CONSTRAINT NN_NAC_PROF CHECK (PROFESOR.NACIMIENTO_USU IS NOT NULL);
ALTER TABLE PROFESORES ADD CONSTRAINT NN_ESDO_PROF CHECK (PROFESOR.ESTADO_USU IS NOT NULL);
ALTER TABLE PROFESORES ADD CONSTRAINT UK_CORREO_PROF UNIQUE (PROFESOR.CORREO_USU);
ALTER TABLE PROFESORES ADD CONSTRAINT FK_TIPODOC_PROF FOREIGN KEY (PROFESOR.TIPODOC_USU) REFERENCES TIPODOCUMENTOS(CODIGO_TIPODOC);
ALTER TABLE PROFESORES ADD CONSTRAINT FK_SEXO_PROF FOREIGN KEY (PROFESOR.SEXO_USU) REFERENCES SEXOS(CODIGO_SEX);
ALTER TABLE PROFESORES ADD CONSTRAINT FK_ESDO_PROF FOREIGN KEY (PROFESOR.ESTADO_USU) REFERENCES ESTADOS(CODIGO_ESTADO);
ALTER TABLE PROFESORES ADD CONSTRAINT FK_IDIOMA_PROF FOREIGN KEY (IDIOMA) REFERENCES IDIOMAS(CODIGO_IDIOMA);

-- Tabla administradores
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT PK_DNI_ADMIN PRIMARY KEY (ADMINISTRADOR.DNI_USU);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT NN_NOM_ADMIN CHECK (ADMINISTRADOR.NOMBRE_USU IS NOT NULL);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT NN_APE1_ADMIN CHECK (ADMINISTRADOR.APELLIDO1_USU IS NOT NULL);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT NN_TIPODOC_ADMIN CHECK (ADMINISTRADOR.TIPODOC_USU IS NOT NULL);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT NN_CORREO_ADMIN CHECK (ADMINISTRADOR.CORREO_USU IS NOT NULL);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT NN_SEXO_ADMIN CHECK (ADMINISTRADOR.SEXO_USU IS NOT NULL);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT NN_CONTRA_ADMIN CHECK (ADMINISTRADOR.CONTRASENNA_USU IS NOT NULL);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT NN_NAC_ADMIN CHECK (ADMINISTRADOR.NACIMIENTO_USU IS NOT NULL);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT NN_ESDO_ADMIN CHECK (ADMINISTRADOR.ESTADO_USU IS NOT NULL);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT UK_CORREO_ADMIN UNIQUE (ADMINISTRADOR.CORREO_USU);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT FK_TIPODOC_ADMIN FOREIGN KEY (ADMINISTRADOR.TIPODOC_USU) REFERENCES TIPODOCUMENTOS(CODIGO_TIPODOC);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT FK_SEXO_ADMIN FOREIGN KEY (ADMINISTRADOR.SEXO_USU) REFERENCES SEXOS(CODIGO_SEX);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT FK_ESDO_ADMIN FOREIGN KEY (ADMINISTRADOR.ESTADO_USU) REFERENCES ESTADOS(CODIGO_ESTADO);
ALTER TABLE ADMINISTRADORES ADD CONSTRAINT FK_ROL_ADMIN FOREIGN KEY (ROL) REFERENCES ROLES(CODIGO_ROL);

-- Tabla niveles matriculados
ALTER TABLE NIVELES_MATRICULADOS ADD CONSTRAINT PK_NIVEL_MATR PRIMARY KEY (NIVEL_MATR.DNI_USU);
ALTER TABLE NIVELES_MATRICULADOS ADD CONSTRAINT NN_FECHA_LIMITE CHECK (FECHA_LIMITE IS NOT NULL);
ALTER TABLE NIVELES_MATRICULADOS ADD CONSTRAINT FK_MATR_EST FOREIGN KEY (NIVEL_MATR.DNI_USU) REFERENCES ESTUDIANTES(ESTUDIANTE.DNI_USU); 
ALTER TABLE NIVELES_MATRICULADOS ADD CONSTRAINT FK_NIVEL_MATR_EST FOREIGN KEY (NIVEL_MATR.COD_NIVEL) REFERENCES NIVELES(CODIGO_NIVEL);

-- Tabla niveles historico
ALTER TABLE NIVELES_HISTORICO ADD CONSTRAINT PK_NIVEL_HIST PRIMARY KEY (NIVEL_HIST.DNI_USU);
ALTER TABLE NIVELES_HISTORICO ADD CONSTRAINT NN_FECHA_FIN CHECK (FECHA_FIN IS NOT NULL);
ALTER TABLE NIVELES_HISTORICO ADD CONSTRAINT FK_HIST_EST FOREIGN KEY (NIVEL_HIST.DNI_USU) REFERENCES ESTUDIANTES(ESTUDIANTE.DNI_USU);
ALTER TABLE NIVELES_HISTORICO ADD CONSTRAINT FK_NIVEL_HIST_EST FOREIGN KEY (NIVEL_HIST.COD_NIVEL) REFERENCES NIVELES(CODIGO_NIVEL);

-- Tabla examen_oral_presentado
ALTER TABLE EXAMEN_ORAL_PRESENTADO ADD CONSTRAINT PK_EXAM_ORAL PRIMARY KEY (ORAL.ID_EXAMEN, ORAL.DNI_EST);
ALTER TABLE EXAMEN_ORAL_PRESENTADO ADD CONSTRAINT NN_NOTA_ORAL CHECK (ORAL.NOTA IS NOT NULL);
ALTER TABLE EXAMEN_ORAL_PRESENTADO ADD CONSTRAINT NN_FECHA_ORAL CHECK (ORAL.FECHA IS NOT NULL);
ALTER TABLE EXAMEN_ORAL_PRESENTADO ADD CONSTRAINT FK_ORAL_EST FOREIGN KEY (ORAL.DNI_EST) REFERENCES ESTUDIANTES(ESTUDIANTE.DNI_USU);
ALTER TABLE EXAMEN_ORAL_PRESENTADO ADD CONSTRAINT FK_ORAL_PROF FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(PROFESOR.DNI_USU);

-- Tabla examen_escrito_presentado
ALTER TABLE EXAMEN_ESCRITO_PRESENTADO ADD CONSTRAINT PK_EXAM_ESCRITO PRIMARY KEY (ESCRITO.ID_EXAMEN, ESCRITO.DNI_EST);
ALTER TABLE EXAMEN_ESCRITO_PRESENTADO ADD CONSTRAINT NN_NOTA_ESCRITO CHECK (ESCRITO.NOTA IS NOT NULL);
ALTER TABLE EXAMEN_ESCRITO_PRESENTADO ADD CONSTRAINT NN_FECHA_ESCRITO CHECK (ESCRITO.FECHA IS NOT NULL);
ALTER TABLE EXAMEN_ESCRITO_PRESENTADO ADD CONSTRAINT NN_ACIERTOS CHECK (CANT_ACIERTO IS NOT NULL);
ALTER TABLE EXAMEN_ESCRITO_PRESENTADO ADD CONSTRAINT FK_ESCRITO_EST FOREIGN KEY (ESCRITO.DNI_EST) REFERENCES ESTUDIANTES(ESTUDIANTE.DNI_USU);
