---------------------------------------------------------------------------------------------
--CREATE TABLES

CREATE TABLE AUDITORIAS_CLASES_PROG (
  CODIGO_AUD NUMBER(3),
  NOMBRE_TABLA VARCHAR2(50),
  OPERACION VARCHAR2(20),
  ID_REGISTRO INTEGER,
  DESCRIPCION VARCHAR2(250),
  FECHA TIMESTAMP
) TABLESPACE TS_BDROO;

CREATE TABLE ESTADOS(
	CODIGO_ESTADO NUMBER(1),
	NOMBRE_ESTADO VARCHAR2(50)
) TABLESPACE TS_BDROO;

CREATE TABLE ESTADOS_EXAMENES (
	CODIGO_ESTADO NUMBER(1),
	ESTADO_EXAMEN VARCHAR2(15)
) TABLESPACE TS_BDROO;

CREATE TABLE ESTADOS_CLASES(
	CODIGO_ESTADO_CLASE NUMBER(1),
	NOMBRE_ESTADO_CLASE VARCHAR2(20)
) TABLESPACE TS_BDROO;

CREATE TABLE ROLES(
	CODIGO_ROL NUMBER(1),
	NOMBRE_ROL VARCHAR2(50)
) TABLESPACE TS_BDROO;

CREATE TABLE SEXOS (
	CODIGO_SEX NUMBER(1),
	NOMBRE_SEX VARCHAR2(20)
) TABLESPACE TS_BDROO;


CREATE TABLE TIPODOCUMENTOS (
	CODIGO_TIPODOC NUMBER(2),
	NOMBRE_DOC VARCHAR2(50)
) TABLESPACE TS_BDROO;


CREATE TABLE NIVELES (
	CODIGO_NIVEL NUMBER(1),
	NIVEL VARCHAR2(5)
) TABLESPACE TS_BDROO;

CREATE TABLE IDIOMAS (
	CODIGO_IDIOMA NUMBER(1),
	IDIOMA VARCHAR2(10)
) TABLESPACE TS_BDROO;

CREATE TABLE SALONES (
	CODIGO_SALON NUMBER(2),
	NUMERO_SALON NUMBER(3),
	CAPACIDAD_SALON NUMBER(1)
) TABLESPACE TS_BDROO;


CREATE TABLE HORAS(
	CODIGO_HORA NUMBER(2),
	HORA_INICIAL VARCHAR2(10),
	HORA_FINAL VARCHAR2(10)
) TABLESPACE TS_BDROO;

CREATE TABLE CLASES (
	CODIGO_CLASE VARCHAR2(10),
	NUMERO_CLASE NUMBER(2),
	DESCRIPCION_CLASE VARCHAR2(100),
	CODIGO_NIVEL_CLASE NUMBER(1)
) TABLESPACE TS_BDROO;

CREATE TABLE CLASES_PROGRAMADAS (
	DNI_EST VARCHAR2(20),
	PROGRAMACION PROGRAMACION_OBJ,
	CODIGO_CLASE VARCHAR2(10),
	ESTADO_CLASE_PROG NUMBER(1)
) TABLESPACE TS_BDROO;

CREATE TABLE CUPOS (
	CODIGO_CUPO NUMBER(5),
	PROGRAMACION PROGRAMACION_OBJ,
	CODIGO_SALON NUMBER(3),
	DNI_PROFESOR VARCHAR2(50),
	ESTUDIANTES_REGISTRADOS NUMBER(1) DEFAULT 0
) TABLESPACE TS_BDROO;

CREATE TABLE EXAMENES (
	NUMERO_EXAMEN NUMBER(2),
	UNIDADES_EXAMEN VARCHAR2(50),
	TEMATICA_EXAMEN VARCHAR2(50),
	CODIGO_CLASE_EXAMEN VARCHAR2(10),
	CODIGO_NIVEL_EXAMEN NUMBER(1)
) TABLESPACE TS_BDROO;

CREATE TABLE EXAMENES_ESCRITOS (
	CODIGO_EXAMEN_ESCRITO NUMBER(2),
	CODIGO_EXAMEN NUMBER(2)
) TABLESPACE TS_BDROO;

CREATE TABLE PREGUNTAS (
	CODIGO_PREGUNTA NUMBER(4),
	CODIGO_EXAMEN_ESCRITO NUMBER(2),
	PREGUNTA VARCHAR2(255)
) TABLESPACE TS_BDROO;

CREATE TABLE RESPUESTAS (
	CODIGO_RESPUESTA NUMBER(4),
	CODIGO_PREGUNTA_RESPUESTA NUMBER(4),
	CONTENIDO_RESPUESTA VARCHAR2(255),
	ACIERTO_RESPUESTA VARCHAR2(10)
) TABLESPACE TS_BDROO;

CREATE TABLE EXAMENES_ORALES (
	CODIGO_EXAMEN_ORAL NUMBER(2),
	CODIGO_EXAMEN NUMBER(2),
	ARCHIVO_URL VARCHAR2(255)
) TABLESPACE TS_BDROO;

CREATE TABLE ESTUDIANTES (
	ESTUDIANTE PERSONA_OBJETO,
	PROMEDIO NUMBER(5,2)
) TABLESPACE TS_BDROO;

CREATE TABLE PROFESORES (
	PROFESOR PERSONA_OBJETO,
	IDIOMA NUMBER(1)
) TABLESPACE TS_BDROO;

CREATE TABLE ADMINISTRADORES (
	ADMINISTRADOR PERSONA_OBJETO,
	ROL NUMBER(1)
) TABLESPACE TS_BDROO;

CREATE TABLE NIVELES_MATRICULADOS(
	NIVEL_MATR DATOS_NIVEL_EST_OBJ,
	FECHA_LIMITE DATE
) TABLESPACE TS_BDROO;

CREATE TABLE NIVELES_HISTORICO(
	NIVEL_HIST DATOS_NIVEL_EST_OBJ,
	FECHA_FIN DATE
) TABLESPACE TS_BDROO;

CREATE TABLE EXAMEN_ORAL_PRESENTADO(
	ORAL EXAM_PRESENTADO_OBJ,
	DNI_PROFESOR VARCHAR2(50)
) TABLESPACE TS_BDROO;

CREATE TABLE EXAMEN_ESCRITO_PRESENTADO(
	ESCRITO EXAM_PRESENTADO_OBJ,
	CANT_ACIERTO NUMBER(1)
) TABLESPACE TS_BDROO;

CREATE TABLE NOTAS (
    ID_EXAMEN NUMBER(2), -- PK FK que se refiere a EXAMEN (NUMERO_EXAMEN)
    DNI_ESTUDIANTE VARCHAR2(50),
    PROMEDIO NUMBER(3,2),
    ESTADO NUMBER(1) -- FK que se refiere a ESTADOS_EXAMENES
) TABLESPACE TS_BDROO;