---------------------------------------------------------------------------------------------
--CREATE TABLES

CREATE TABLE AUDITORIAS_CLASES_PROG (
  CODIGO_AUD NUMBER(3),
  NOMBRE_TABLA VARCHAR2(50),
  OPERACION VARCHAR2(20),
  ID_REGISTRO INTEGER,
  DESCRIPCION VARCHAR2(250),
  FECHA TIMESTAMP,
  CONSTRAINT PK_AUD_CLAS_PROG PRIMARY KEY (CODIGO_AUD)
);

CREATE TABLE ESTADOS(
	CODIGO_ESTADO NUMBER(1),
	NOMBRE_ESTADO VARCHAR2(50),
	CONSTRAINT PK_CODIGO_ESTADO PRIMARY KEY (CODIGO_ESTADO),
	CONSTRAINT NN_NOMBRE_ESTADO CHECK (NOMBRE_ESTADO IS NOT NULL)
) TABLESPACE TS_BDROO;

CREATE TABLE ROLES(
	CODIGO_ROL NUMBER(1),
	NOMBRE_ROL VARCHAR2(50),
	CONSTRAINT PK_COD_ROL PRIMARY KEY (CODIGO_ROL),
	CONSTRAINT NN_NOMBRE_ROL CHECK (NOMBRE_ROL IS NOT NULL)
) TABLESPACE TS_BDROO;

CREATE TABLE SEXOS (
	CODIGO_SEX NUMBER(1),
	NOMBRE_SEX VARCHAR2(20),
	CONSTRAINT PK_CODIGO_SEX PRIMARY KEY (CODIGO_SEX),
	CONSTRAINT NN_NOMBRE_SEX CHECK (NOMBRE_SEX IS NOT NULL)
) TABLESPACE TS_BDROO;


CREATE TABLE TIPODOCUMENTOS (
	CODIGO_TIPODOC NUMBER(2),
	NOMBRE_DOC VARCHAR2(50),
	CONSTRAINT PK_COD_TIPODOC PRIMARY KEY (CODIGO_TIPODOC),
	CONSTRAINT NN_NOM_TIPODOC CHECK (NOMBRE_DOC IS NOT NULL)
) TABLESPACE TS_BDROO;


CREATE TABLE NIVELES (
	CODIGO_NIVEL NUMBER(1),
	NIVEL VARCHAR2(5),
	CONSTRAINT PK_CODIGO_NIVEL PRIMARY KEY (CODIGO_NIVEL),
	CONSTRAINT NN_NIVEL CHECK (NIVEL IS NOT NULL)
) TABLESPACE TS_BDROO;

CREATE TABLE IDIOMAS (
	CODIGO_IDIOMA NUMBER(1),
	IDIOMA VARCHAR2(10),
	CONSTRAINT PK_COD_IDIOMA PRIMARY KEY (CODIGO_IDIOMA),
	CONSTRAINT NN_IDIOMA CHECK (IDIOMA IS NOT NULL)
) TABLESPACE TS_BDROO;

CREATE TABLE ESTUDIANTES (
	ESTUDIANTE PERSONA_OBJETO,
	PROMEDIO NUMBER(5,2)
) TABLESPACE TS_BDROO;

CREATE TABLE PROFESORES (
	PROFESOR PERSONA_OBJETO,
	IDIOMA NUMBER(1)
) TABLESPACE TS_BDROO;

CREATE TABLE ADMINISTRADORES (
	ADMINISTRADOR PERSONA_OBJETO,
	ROL NUMBER(1)
) TABLESPACE TS_BDROO;

CREATE TABLE NIVELES_MATRICULADOS(
	NIVEL_MATR DATOS_NIVEL_EST_OBJ,
	FECHA_LIMITE DATE
) TABLESPACE TS_BDROO;

CREATE TABLE NIVELES_HISTORICO(
	NIVEL_HIST DATOS_NIVEL_EST_OBJ,
	FECHA_FIN DATE
) TABLESPACE TS_BDROO;

CREATE TABLE EXAMEN_ORAL_PRESENTADO(
	ORAL EXAM_PRESENTADO_OBJ,
	DNI_PROFESOR VARCHAR2(50)
) TABLESPACE TS_BDROO;

CREATE TABLE EXAMEN_ESCRITO_PRESENTADO(
	ESCRITO EXAM_PRESENTADO_OBJ,
	CANT_ACIERTO NUMBER(1)
) TABLESPACE TS_BDROO;

