--DROP TABLES
DROP TABLE AUDITORIAS_CLASES_PROG;
DROP TABLE ADMINISTRADORES;
DROP TABLE ROLES;
DROP TABLE EXAMEN_ESCRITO_PRESENTADO;
DROP TABLE EXAMEN_ORAL_PRESENTADO;
DROP TABLE PROFESORES;
DROP TABLE NIVELES_MATRICULADOS;
DROP TABLE NIVELES_HISTORICO;
DROP TABLE ESTUDIANTES;
DROP TABLE ESTADOS;
DROP TABLE SEXOS;
DROP TABLE TIPODOCUMENTOS;
DROP TABLE NIVELES;

--DROP TYPES
DROP TYPE PERSONA_OBJETO;
DROP TYPE DATOS_NIVEL_EST_OBJ;
DROP TYPE EXAM_PRESENTADO_OBJ;