--DROP TABLES
--DROP TABLE CLASES_PROGRAMADAS;
--DROP TABLE CUPOS;
DROP TABLE AUDITORIAS_CLASES_PROG;
DROP TABLE NIVELES_MATRICULADOS;
DROP TABLE NIVELES_HISTORICO;
DROP TABLE ADMINISTRADORES;
DROP TABLE ROLES;
DROP TABLE PROFESORES;
DROP TABLE IDIOMAS;
DROP TABLE NOTAS;
DROP TABLE ESTADOS_EXAMENES;
DROP TABLE EXAMEN_ESCRITO_PRESENTADO;
DROP TABLE EXAMEN_ORAL_PRESENTADO;
DROP TABLE RESPUESTAS;
DROP TABLE PREGUNTAS;
DROP TABLE EXAMENES_ORALES;
DROP TABLE EXAMENES_ESCRITOS;
DROP TABLE EXAMENES;
DROP TABLE CLASES;
DROP TABLE ESTUDIANTES;
DROP TABLE ESTADOS;
DROP TABLE SEXOS;
DROP TABLE TIPODOCUMENTOS;
DROP TABLE NIVELES;
DROP TABLE HORAS;
DROP TABLE SALONES;

--DROP TYPES
DROP TYPE PERSONA_OBJETO;
DROP TYPE DATOS_NIVEL_EST_OBJ;
DROP TYPE EXAM_PRESENTADO_OBJ;