--SECUENCIAS
DROP SEQUENCE SEQ_AUD_CLAS_PROG ;
CREATE SEQUENCE SEQ_AUD_CLAS_PROG 
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP SEQUENCE SEQ_CUPOS;
CREATE SEQUENCE SEQ_CUPOS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;